export const ITEM_SEARCH_REQUEST = 'ITEM_SEARCH_REQUEST';
export const ITEM_SEARCH_SUCCESS = 'ITEM_SEARCH_SUCCESS';
export const ITEM_SEARCH_FAILURE = 'ITEM_SEARCH_FAILURE';
export const WATCHLIST_ADD = 'WATCHLIST_ADD';
export const WATCHLIST_REMOVE = 'WATCHLIST_REMOVE';
