export const ITEM_SEARCH_REQUEST = 'ITEM_SEARCH_REQUEST';
export const ITEM_SEARCH_SUCCESS = 'ITEM_SEARCH_SUCCESS';
export const ITEM_SEARCH_FAILURE = 'ITEM_SEARCH_FAILURE';
export const WATCHLIST_ADD = 'WATCHLIST_ADD';
export const WATCHLIST_REMOVE = 'WATCHLIST_REMOVE';
export const WATCHLIST_FETCH_REQUEST = 'WATCHLIST_FETCH_REQUEST';
export const WATCHLIST_FETCH_SUCCESS = 'WATCHLIST_FETCH_SUCCESS';
export const WATCHLIST_FETCH_FAILURE = 'WATCHLIST_FETCH_FAILURE';
